services:
  restaurant-api:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.backend
      # If your Dockerfile needs .env, ensure it's in the build context (default for Compose)
    ports:
      - "8080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - JwtSettings__Issuer=${JwtSettings__Issuer}
      - JwtSettings__Audience=${JwtSettings__Audience}
      - JwtSettings__ExpiryMinutes=${JwtSettings__ExpiryMinutes}
    depends_on:
      - sqlserver
    networks:
      - restaurant-network

  # Testing services moved to separate docker-compose.test.yml for CI/CD
  # restaurant-api-tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfiles/Dockerfile.backend.tests
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Testing
  #     - ConnectionStrings__DefaultConnection=Server=sqlserver-test;Database=${DB_NAME}_Test;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;
  #   depends_on:
  #     - sqlserver-test
  #   networks:
  #     - restaurant-network
  #   profiles:
  #     - testing

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - restaurant-network

  # Testing database moved to separate docker-compose.test.yml for CI/CD
  # sqlserver-test:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=${DB_PASSWORD}
  #     - MSSQL_PID=Express
  #   ports:
  #     - "1434:1433"
  #   volumes:
  #     - sqlserver_test_data:/var/opt/mssql
  #   networks:
  #     - restaurant-network
  #   profiles:
  #     - testing

volumes:
  sqlserver_data:
  # Testing volume moved to separate docker-compose.test.yml for CI/CD
  # sqlserver_test_data:

networks:
  restaurant-network:
    driver: bridge
