apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "{{ .Values.mssql.acceptEula }}"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: SA_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: DB_USER
            - name: MSSQL_PID
              value: "{{ .Values.mssql.edition }}"
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldata
          persistentVolumeClaim:
            claimName: sqlserver-pvc
