apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
  selector:
    app: sqlserver
