replicaCount: 1
image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2022-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1433

resources: {}

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

mssql:
  edition: "Developer"
  acceptEula: "Y"
